### ISSUE TITLE
Win 下引入，mkdir 的问题

### ISSUE THREAD

**Issue by harryisfish** [rumsystem/quorum-sdk-electron-main#1]
源码仓库：[https://github.com/Tymon42/electron-vue-test](https://github.com/Tymon42/electron-vue-test)  
平台：win11  
安装 `quorum-sdk-electron-main` 之后，运行 `yarn dev` ，命令行报如下错误：  
```shell
$ rimraf dist && vite

  VITE v3.0.9  ready in 1129 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
DSB 💻 Mode:  Development
DSB 💠 Application type:  electron
DSB ✅ Prebuild succeeded!
DSB 🚦 Wait for renderer: http://127.0.0.1:5173
DSB ⚡ Run main file: dist/main/index.js

{
  quorumBinPath: 'C:\\Users\\why00\\Documents\\project\\electron-vue-test\\dist\\main\\node_modules\\quorum-bin'
}
[Error: ENOENT: no such file or directory, mkdir 'C:\Users\why00\Documents\project\electron-vue-test\dist\main\node_modules\quorum-bin'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\Users\\why00\\Documents\\project\\electron-vue-test\\dist\\main\\node_modules\\quorum-bin'
}
[Error: ENOENT: no such file or directory, mkdir 'C:\Users\why00\Documents\project\electron-vue-test\dist\main\node_modules\quorum-bin\certs'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\Users\\why00\\Documents\\project\\electron-vue-test\\dist\\main\\node_modules\\quorum-bin\\certs'
}
09:16:20.574 > Error: C:\Users\why00\Documents\project\electron-vue-test\dist\main\node_modules\quorum-bin\certs does not exist.
    at watch (C:\Users\why00\Documents\project\electron-vue-test\node_modules\node-watch\lib\watch.js:475:7)
    at Object.init (C:\Users\why00\Documents\project\electron-vue-test\node_modules\quorum-sdk-electron-main\index.js:191:5)
```

**Comment by jklfds9527** [comment]
> 源码仓库：https://github.com/Tymon42/electron-vue-test 平台：win11 安装 `quorum-sdk-electron-main` 之后，运行 `yarn dev` ，命令行报如下错误：
> 
> ```shell
> $ rimraf dist && vite
> 
>   VITE v3.0.9  ready in 1129 ms
> 
>   ➜  Local:   http://127.0.0.1:5173/
>   ➜  Network: use --host to expose
> DSB 💻 Mode:  Development
> DSB 💠 Application type:  electron
> DSB ✅ Prebuild succeeded!
> DSB 🚦 Wait for renderer: http://127.0.0.1:5173
> DSB ⚡ Run main file: dist/main/index.js
> 
> {
>   quorumBinPath: 'C:\\Users\\why00\\Documents\\project\\electron-vue-test\\dist\\main\\node_modules\\quorum-bin'
> }
> [Error: ENOENT: no such file or directory, mkdir 'C:\Users\why00\Documents\project\electron-vue-test\dist\main\node_modules\quorum-bin'] {
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'mkdir',
>   path: 'C:\\Users\\why00\\Documents\\project\\electron-vue-test\\dist\\main\\node_modules\\quorum-bin'
> }
> [Error: ENOENT: no such file or directory, mkdir 'C:\Users\why00\Documents\project\electron-vue-test\dist\main\node_modules\quorum-bin\certs'] {
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'mkdir',
>   path: 'C:\\Users\\why00\\Documents\\project\\electron-vue-test\\dist\\main\\node_modules\\quorum-bin\\certs'
> }
> 09:16:20.574 > Error: C:\Users\why00\Documents\project\electron-vue-test\dist\main\node_modules\quorum-bin\certs does not exist.
>     at watch (C:\Users\why00\Documents\project\electron-vue-test\node_modules\node-watch\lib\watch.js:475:7)
>     at Object.init (C:\Users\why00\Documents\project\electron-vue-test\node_modules\quorum-sdk-electron-main\index.js:191:5)
> ```

引入 quorum-sdk-electron-main 后，需要按照实际使用的框架来调整 quorum 相关路径的设置。项目介绍里面的配置只是一般的 electron 配置。我看了你的项目，根据你使用的这个构建框架做如下调整：
```js
Quorum.init({
	quorumBinPath: app.isPackaged
    ? `${process.resourcesPath}\\quorum-bin` : `${app.getAppPath()}\\node_modules\\quorum-bin`,
});
```

修改为

```js
Quorum.init({
	quorumBinPath: app.isPackaged
    ? `${process.resourcesPath}\\quorum-bin` : `${process.cwd()}\\node_modules\\quorum-bin`,
});
```
文档里提到的 extraResources 设置不要添加在 package.json 里，意思是把他们从你现在的 package.json 里面移除掉，当然你不移除也没影响，在你使用的这个项目框架里，放在这个地方其实没有生效。在这里把说明里面 build:{ } 里面的内容放到 electron-builder.config.js 里就可以生效了，按照下面的这个来修改即可：
```js
/**
 * @type {import('electron-builder').Configuration}
 * @see https://www.electron.build/configuration/configuration
 */
const config = {
  directories: {
    output: 'dist/electron',
  },
  publish: null,
  npmRebuild: false,
  electronDownload: {
    mirror: 'https://npm.taobao.org/mirrors/electron/',
  },
  files: [
    'dist/main/**/*',
    'dist/preload/**/*',
    'dist/render/**/*',
  ],
  "mac": {
    "extraResources": [
      {
        "from": "node_modules/quorum-bin/quorum_darwin",
        "to": "quorum-bin/quorum_darwin"
      }
    ]
  },
  "win": {
    "extraResources": [
      {
        "from": "node_modules/quorum-bin/quorum_win.exe",
        "to": "quorum-bin/quorum_win.exe"
      }
    ]
  },
  "linux": {
    "extraResources": [
      {
        "from": "node_modules/quorum-bin/quorum_linux",
        "to": "quorum-bin/quorum_linux"
      }
    ]
  }
}

module.exports = config
```

完成上面两处修改之后，yarn dev 和 yarn build 都能正常工作了。

**Comment by harryisfish** [comment]
thx！
